name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/docs.yml'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup mdBook
      run: |
        mkdir bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.34/mdbook-v0.4.34-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$(pwd)/bin" >> $GITHUB_PATH

    - name: Build Documentation
      run: |
        # Create book.toml if it doesn't exist
        if [ ! -f docs/book.toml ]; then
          cat > docs/book.toml << EOF
        [book]
        authors = ["Your Name"]
        language = "en"
        multilingual = false
        src = "src"
        title = "Dev-Ops TUI Documentation"
        EOF
        fi

        # Create src directory and index if they don't exist
        mkdir -p docs/src
        if [ ! -f docs/src/SUMMARY.md ]; then
          cat > docs/src/SUMMARY.md << EOF
        # Summary

        - [Introduction](README.md)
        - [Installation](installation.md)
        - [Usage](usage.md)
        - [API Reference](api.md)
        EOF
        fi

        # Copy main README as intro
        cp README.md docs/src/README.md

        # Build the book
        cd docs && mdbook build

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'docs/book/html'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 