name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bash-version: ['4.4', '5.0', '5.1']

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y dialog
        sudo apt-get install -y bash="${{ matrix.bash-version }}*" || true

    - name: Check Bash version
      run: bash --version

    - name: Run Tests
      run: |
        chmod +x ./tests/run_tests.sh
        ./tests/run_tests.sh

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: './tui'
        severity: warning

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: '.'
        severity: style